spring:
  application:
    name: chat

  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

chat:
  ai:
    api-key: AIzaSyDBEaYnHLzhowkn1UCfPj4hNLEEegZSx2o